### ISSUE TITLE
Make n_jobs_percentage configurable

### ISSUE THREAD

**Issue by asmacdo** [con/opfvta-replication-2023#18]
Currently, n_jobs_percentage is hard coded in the invocation of SAMRI.

https://bitbucket.org/TheChymera/opfvta/src/656cd87d6efb4782f149a858f7f2a65dadc510be/prepare/preprocess.py#lines-25

@TheChymera and I discussed this and we identified 2 options:

1. Have SAMRI read in an environment variable
2. Have opfvta read in an environment variable

IMO, a user of opfvta should not need to know the internals of SAMRI, and should not need to configure it directly. SAMRI is already able to use multiple values for this since the value is passed by opfvta. So I suggest that opfvta should read in this value and also set a sane default. 

On the other hand...

I do not think SAMRI should be deploying jobs based on the available resources of the machine. Instead it should deploy jobs based on **allocated** resources. ie, instead of `n_jobs_percentage`. This will play nicer with others when using on a shared environment. For local "as fast as possible" usage, perhaps lets leave n_jobs_percentage, but it would be nice to be able to limit by `max_simultaneous_jobs` directly.

**Comment by TheChymera** [comment]
I originally introduced `n_jobs_percentage` because believe it or not both of these large analyses will run on either my laptop or desktop, the idea was to have it run on both of them “as fast as possible” but without OOM-ing. I guess we could have both, but the more I think about it, the more I think this really should be a SAMRI issue. OPFVTA is doing nothing wrong, it's just relying on SAMRI, which lacks support for OPFVTA to adequately control the resources.

**Comment by TheChymera** [comment]
This is I think a SAMRI issue. Tracking it over there, reopen if this becomes relevant here again.
