### ISSUE TITLE
Provide container recipe with latex et al dependencies to compile paper fully

### ISSUE THREAD

**Issue by yarikoptic** [con/opfvta-replication-2023#4]
Should be trivial AFAIK.

I don't think we should sweat to automate build/pushing via CI.  Just build and push manually into some docker hub.  @asmacdo has accounts.

Might even be worth taking one from JOSS and building on top may be?
then Makefile might even make use of it in some rule which would do the build in container with e.g. like singularity

```makefile
all-container:
	singularity exec make all
```

can be changed to docker but then watchout for the user id to be mapped etc, so produced artifacts are owned by original user. We do it in https://github.com/ReproNim/containers/blob/master/scripts/singularity_cmd#L140

**Comment by asmacdo** [comment]
I was able to use blang/latex image out of the box! There were some permissions issues, probably because the original image is intended to be run as root (originally for docker, not podman). I brute forced it with `sudo`, I can look into fixing that later.


https://github.com/con/opfvta-replication-2023/commit/b5b69cb85bbff83ea7462403223d133c0a069d6e

**Comment by asmacdo** [comment]
The recipe lives in code/images/Containerfile.latex

The image lives on dockerhub https://hub.docker.com/r/asmacdo/latex-biber (use `docker pull asmacdo/latex-biber`)

The makefile uses this image for `make article.pdf`
